version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: jwt_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: jwt_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

